# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd309465fe8332f3a0daeb789560cb129be6780de24f394d97409c6f100d0b12e3b0532fade29a77c65989a1691ba5e9e7d155abefff9ffd1d204b8f20b4fe8

test:
  secret_key_base: feb077c542944bb77e1a8bd83cde5a670de242aecaee34b5547b9d3e3e2ca50bfec4a983270ba95627031dab966c3f60c676a14296b61325d3ebe4124961ea23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
